#  .circleci/config.yml
#
#   DecoderThing
#   Created by Duncan Wallace 12/10/2024
#   Copyright © 2024. Duncwa LLC.  All rights reserved

version: 2.1

# ...
orbs:
  macos: circleci/macos@2

jobs:
  build-and-test:
    macos:
      xcode: 16.1
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: test
    steps:
      - run:
          name: Available Ruby Versions
          command:  |
            rbenv install --list-all
      - macos/preboot-simulator:
          version: "18.1"
          platform: "iOS"
          device: "iPhone 16 Pro Max"
      - checkout
      - run:
          name: Set Ruby Version
          command: |
            echo "ruby-3.2.5" > .ruby-version
      - run: bundle install
      - run:
          name: Fastlane
          command: bundle exec fastlane test_ios_pra
      - store_artifacts:
          path: output
      - store_test_results:
          path: output/scan

  pra:
    macos:
      xcode: 16.1
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: pra
    steps:
      - macos/preboot-simulator:
          version: "18.1"
          platform: "iOS"
          device: "iPhone 16 Pro Max"
      - checkout
      - run:
          name: Set Ruby Version
          command:  |
            echo "ruby-3.2.5" > .ruby-version
      - run: bundle install
      - run:
          name: Fastlane
          command: bundle exec fastlane test_ios_pra
      - store_artifacts:
          path: output
  qa:
    macos:
      xcode: 16.1
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: qa
    steps:
      - macos/preboot-simulator:
          version: "18.1"
          platform: "iOS"
          device: "iPhone 16 Pro Max"
      - checkout
      - run:
          name: Set Ruby Version
          command:  |
            echo "ruby-3.2.5" > .ruby-version
      - run: bundle install
      - run:
          name: Fastlane
          command: bundle exec fastlane test_ios_qa
      - store_artifacts:
          path: output

workflows:
  build-test-pra:
    jobs:
      - build-and-test
      - pra:
          filters:
            branches:
              only: /[A-Za-z]+-\d+-[A-Za-z0-9-]+/
          requires:
            - build-and-test
  build-test-qa:
    jobs:
      - build-and-test
      - qa:
          filters:
            branches:
              only: /QA-[A-Za-z]+-\d+-[A-Za-z0-9-]+/
          requires:
            - build-and-test
